[default_session]
startup_command = "nvim -c ':Telescope find_files'"

# dotfiles configs
[[session]]
name = "dotfiles"
path = "~/dotfiles/"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "scripts"
path = "~/dotfiles/scripts/"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "zsh config"
path = "~/dotfiles/"
startup_command = "nvim zshrc"

[[session]]
name = "tmux config"
path = "~/dotfiles/"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config"
path = "~/dotfiles/config/nvim"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "sesh config"
path = "~/dotfiles/config/sesh/"
startup_command = "nvim sesh.toml"

# python projects
[[session]]
name = "T-Rex-Azure-Personalised-Rewards"
path = "~/code/Azure/T-Rex-Azure-Personalised-Rewards"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "T-Rex-Azure-Core"
path = "~/code/Azure/T-Rex-Azure-Core"
startup_command = "nvim -c ':Telescope find_files'"




